name = "focusguard"
pages_build_output_dir = "dist"
compatibility_date = "2024-11-01"
compatibility_flags = [ "nodejs_compat" ]

# KV Binding for Session/JWT Validation
[[kv_namespaces]]
binding = "SESSIONS_KV"
id = "22b87e67e3a944c68dfb7d5f4d3cbb1c"

[[d1_databases]]
binding = "DB"
database_name = "focusguard_db"
database_id = "3424da7e-190a-49be-93bb-1ec9ad7e190f"
